### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by macon** [nathanpovo/NullableReferenceTypes.StrictMode#1]
I get the following when compiling:
```
/usr/local/share/dotnet/sdk/8.0.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): error NU5019: File not found: '/Users/XXX/git/NullableReferenceTypes.StrictMode/NullableReferenceTypes.StrictMode.Package/bin/Debug/net6.0/NullableReferenceTypes.StrictMode.CodeFixes.dll'. [/Users/XXX/git/NullableReferenceTypes.StrictMode/NullableReferenceTypes.StrictMode.Package/NullableReferenceTypes.StrictMode.Package.csproj
```

**Comment by nathanpovo** [comment]
Thanks for mentioning this.

I somehow forgot to remove this reference to the code fix project in commit 5505c623d16708f4a550750cc1593378ddf44258.

The project that was failing (the package project) isn't that important since it's only used for packaging the project. I mostly build the analyser project itself or the testing project.
